# Generated by Django 3.2.12 on 2022-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runder_app', '0004_auto_20220303_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
    ]
