# Generated by Django 3.2.12 on 2022-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runder_app', '0005_auto_20220303_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
    ]
