# Generated by Django 3.2.12 on 2022-03-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runder_app', '0006_userprofileinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password',
        ),
    ]
